# CI de Nível 01 - Disparo manual a partir de 1 clique

name: 'Execução Manual'

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando o driver UiAutomator2
        run: npx appium driver install uiautomator2  

      - name: Iniciando Appium com --allow-cors
        run: |
          npx appium --allow-cors &  # Inicia o Appium em background
          sleep 10                   # Aguarda 10 segundos para o Appium iniciar  
     
      - name: Testes E2E (end-to-end)
        run: npm run test:android

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./reports
